// POST /api/twin/voice-note — ingest a spoken note.
//
// Two accepted body shapes:
//
//   Fast path (preferred):   { transcript: string, date?: string, notes?: string }
//     The client already transcribed the note live (Deepgram, or Web Speech as
//     fallback) and the user watched those words stream in. We store that text
//     directly via tools/storage.js#addVoiceNote — no audio upload, no Whisper
//     round trip, near-instant save.
//
//   Whisper fallback:        { audio_base64: string, mime_type: string, date?: string }
//     Used only when no live transcript exists (both live engines failed during
//     the session). We decode the audio, transcribe with OpenAI Whisper
//     (whisper-1), then hand the transcript to the same addVoiceNote path.
//
// Either way storage runs through addVoiceNote — the same path the MCP tool
// uses — so extraction + tagging + Pinecone upsert behave identically
// regardless of capture surface.
//
// We hard-cap the decoded audio at 8 MB to stay under Vercel's request-body
// limit and well below Whisper's 25 MB per-file limit (a normal voice note
// under ~5 min in webm/opus is < 2 MB).

import OpenAI from 'openai';
import { methodGuard, runTwin } from '../../lib/twin-api.js';
import { addVoiceNote } from '../../tools/storage.js';
import { UserError } from '../../lib/errors.js';
import { generateAck } from '../../lib/ack.js';

const MAX_AUDIO_BYTES = 8 * 1024 * 1024;

let _openai = null;
function getOpenAI() {
  if (!_openai) _openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });
  return _openai;
}

// Store a transcript and return it with an in-voice acknowledgement.
// Shared by both the fast path and the Whisper fallback so storage + ack
// behave identically. The ack is generated by Sonnet rather than a templated
// success string, so even a thin extraction gets a thoughtful reply.
async function storeAndAck(ctx, { transcript, date, notes }) {
  const result = await addVoiceNote(ctx, { transcript, date, notes });
  const ack = await generateAck({
    type:           'voice-note',
    title:          result.source_ref,
    extractedItems: result.items_extracted || 0,
    quality:        result.stored ? 'typical' : 'thin',
  });
  return { ...result, ack };
}

export default async function handler(req, res) {
  if (!methodGuard(req, res, ['POST'])) return;

  const { audio_base64, mime_type, filename, date, notes, transcript } = req.body || {};

  // ── Fast path: a live transcript already exists. Store it directly. ──────────
  if (typeof transcript === 'string' && transcript.trim()) {
    return runTwin(req, res, {
      toolName: 'add_voice_note',
      cap:      'storage',
      fn: (ctx) => storeAndAck(ctx, { transcript, date, notes }),
    });
  }

  // ── Whisper fallback: no live transcript, so transcribe the uploaded audio. ──
  if (typeof audio_base64 !== 'string' || !audio_base64) {
    return res.status(400).json({ error: 'transcript or audio_base64 is required' });
  }
  if (typeof mime_type !== 'string' || !mime_type) {
    return res.status(400).json({ error: 'mime_type is required (e.g. audio/webm)' });
  }

  let audioBuf;
  try {
    audioBuf = Buffer.from(audio_base64, 'base64');
  } catch {
    return res.status(400).json({ error: 'audio_base64 is not valid base64' });
  }
  if (audioBuf.length === 0) {
    return res.status(400).json({ error: 'Decoded audio is empty' });
  }
  if (audioBuf.length > MAX_AUDIO_BYTES) {
    return res.status(413).json({
      error: `Audio exceeds ${MAX_AUDIO_BYTES / 1024 / 1024} MB limit (got ${(audioBuf.length / 1024 / 1024).toFixed(1)} MB).`,
    });
  }

  return runTwin(req, res, {
    toolName: 'add_voice_note',
    cap:      'storage',
    fn: async (ctx) => {
      // Transcribe via Whisper. The OpenAI SDK accepts a Web `File`
      // (global in Node 20+) for the file field.
      const ext = mime_type.includes('webm') ? 'webm'
                : mime_type.includes('mp4')  ? 'm4a'
                : mime_type.includes('wav')  ? 'wav'
                : 'webm';
      const file = new File([audioBuf], filename || `voice.${ext}`, { type: mime_type });

      let whisperText;
      try {
        const result = await getOpenAI().audio.transcriptions.create({
          file,
          model: 'whisper-1',
        });
        whisperText = result.text || '';
      } catch (err) {
        // Surface a clear, safe message — Whisper failures are usually
        // bad audio or a quota issue.
        throw new UserError(`Could not transcribe the recording: ${err?.message || 'unknown error'}.`);
      }

      if (!whisperText.trim()) {
        throw new UserError('The recording came back empty. Try again. Speak clearly into the mic.');
      }

      return storeAndAck(ctx, { transcript: whisperText, date, notes });
    },
  });
}
